# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=140)),
                ('Image', models.ImageField(upload_to='Atelier/Image/')),
                ('Descritpion', models.TextField()),
                ('nBplace', models.IntegerField()),
                ('PlaceReserver', models.IntegerField(default=0)),
                ('prix', models.IntegerField()),
                ('prixAdh', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('Rang', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=140)),
                ('Image', models.ImageField(upload_to='Machine/Image/')),
                ('Descritpion', models.TextField()),
                ('Cout', models.IntegerField()),
                ('CoutAdh', models.IntegerField()),
                ('fichier', models.FileField(upload_to='Machine/File/')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=140)),
                ('Image', models.ImageField(upload_to='Projet/Image/')),
                ('fichier', models.FileField(upload_to='Projet/File/')),
                ('Contenue', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Categorie', models.ManyToManyField(to='app.Categorie')),
                ('Licence', models.ManyToManyField(to='app.Licences')),
                ('Machine', models.ManyToManyField(to='app.Machine')),
                ('Materiaux', models.ManyToManyField(to='app.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='User/Image/')),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('NewsLetter', models.BooleanField(default=True)),
                ('Rang', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='Utilisateur',
            field=models.ManyToManyField(to='app.utilisateur'),
        ),
        migrations.AddField(
            model_name='machine',
            name='Projet',
            field=models.ManyToManyField(to='app.Projet'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='UtilisateurInscrit',
            field=models.ManyToManyField(to='app.utilisateur'),
        ),
    ]
