# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 16:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to=None)),
                ('Descritpion', models.CharField(max_length=1500)),
                ('nBplace', models.IntegerField()),
                ('PlaceReserver', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to=None)),
                ('Descritpion', models.CharField(max_length=1500)),
                ('Cout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to=None)),
                ('fichier', models.FileField(upload_to=None)),
                ('Contenue', models.CharField(max_length=1500)),
                ('Date', models.DateTimeField()),
                ('Categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
                ('Licence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Licences')),
                ('Machine', models.ManyToManyField(to='app.Machine')),
                ('Materiaux', models.ManyToManyField(to='app.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to=None)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='Utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
    ]
