# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=30)),
                ('Image', models.ImageField(height_field=300, upload_to='Atelier/Image/', width_field=300)),
                ('Descritpion', models.CharField(max_length=1500)),
                ('nBplace', models.IntegerField()),
                ('PlaceReserver', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomLab', models.CharField(max_length=30)),
                ('AdresseContact', models.CharField(max_length=30)),
                ('Rue', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=30)),
                ('CodePostal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=30)),
                ('Image', models.ImageField(height_field=300, upload_to='Machine/Image/', width_field=300)),
                ('Descritpion', models.CharField(max_length=1500)),
                ('Cout', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('Image', models.ImageField(height_field=300, upload_to='Projet/Image/', width_field=300)),
                ('fichier', models.FileField(upload_to='Projet/File/')),
                ('Contenue', models.CharField(max_length=1500)),
                ('Date', models.DateTimeField()),
                ('Categorie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Categorie')),
                ('Licence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Licences')),
                ('Machine', models.ManyToManyField(to='app.Machine')),
                ('Materiaux', models.ManyToManyField(to='app.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(height_field=300, upload_to='User/Image/', width_field=300)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='Utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.utilisateur'),
        ),
    ]
