# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='prixAdh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='machine',
            name='CoutAdh',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='Image',
            field=models.ImageField(upload_to='Atelier/Image/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Image',
            field=models.ImageField(upload_to='Machine/Image/'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Image',
            field=models.ImageField(upload_to='Projet/Image/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='Image',
            field=models.ImageField(upload_to='User/Image/'),
        ),
    ]
