# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomLab', models.CharField(max_length=30)),
                ('AdresseContact', models.CharField(max_length=30)),
                ('Rue', models.CharField(max_length=150)),
                ('ville', models.CharField(max_length=30)),
                ('CodePostal', models.CharField(max_length=30)),
            ],
        ),
    ]
