# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160114_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextStockage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='atelier',
            name='Descritpion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TextStockage'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Descritpion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TextStockage'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='Contenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TextStockage'),
        ),
    ]
