# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160118_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='Categorie',
        ),
        migrations.AddField(
            model_name='projet',
            name='Categorie',
            field=models.ManyToManyField(to='app.Categorie'),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='Licence',
        ),
        migrations.AddField(
            model_name='projet',
            name='Licence',
            field=models.ManyToManyField(to='app.Licences'),
        ),
    ]
