# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160114_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAtelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TextMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TextProjet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='atelier',
            name='Descritpion',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='Descritpion',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='Contenue',
        ),
        migrations.DeleteModel(
            name='TextStockage',
        ),
        migrations.AddField(
            model_name='textprojet',
            name='Projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Projet'),
        ),
        migrations.AddField(
            model_name='textmachine',
            name='Machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Machine'),
        ),
        migrations.AddField(
            model_name='textatelier',
            name='Atelier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Atelier'),
        ),
    ]
