# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160119_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
