# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='fichier',
            field=models.FileField(default=None, upload_to='Machine/File/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atelier',
            name='Titre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='machine',
            name='Titre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=140),
        ),
    ]
