# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160114_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textatelier',
            name='Atelier',
        ),
        migrations.RemoveField(
            model_name='textmachine',
            name='Machine',
        ),
        migrations.RemoveField(
            model_name='textprojet',
            name='Projet',
        ),
        migrations.AddField(
            model_name='atelier',
            name='Descritpion',
            field=models.TextField(default='toto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='Descritpion',
            field=models.TextField(default='toto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projet',
            name='Contenue',
            field=models.TextField(default='toto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TextAtelier',
        ),
        migrations.DeleteModel(
            name='TextMachine',
        ),
        migrations.DeleteModel(
            name='TextProjet',
        ),
    ]
