# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160114_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='CoutAdh',
            field=models.IntegerField(),
        ),
    ]
