# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160125_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='Rang',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='Rang',
            field=models.IntegerField(default=0),
        ),
    ]
