# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160114_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='UtilisateurInscrit',
            field=models.ManyToManyField(to='app.utilisateur'),
        ),
    ]
